module.exports = [
  "Salar De Uyuni",
  "Lake Natron",
  "Die Rakotzbrück",
  "Spotted Lake Khiluk",
  "Slope Point",
  "Dead Vlei",
  "Underwater Park",
  "Eternal Flame Falls",
  "Tunnel Of Love",
  "Christ Of The Abyss",
  "The Silfra Rift",
  "Caño Cristales",
  "Jellyfish Lake",
  "Blood Falls",
  "Painted Hills",
  "Confluence Of Rhone And Arve Rivers",
  "Sea Of Stars",
  "Huashan Mountain",
  "Nelson Lakes National Park",
  "Giant Crystal Cave",
  "Vinicunca Rainbow Mountain",
  "Yonaguni Monument",
  "Crooked Forest",
  "Pink Sands Beach",
  "Richat Structure",
  "Great Blue Hole",
  "Dead Sea",
  "Lake Retba",
  "The Wave",
  "Mt. Kelimutu",
  "Al Naslaa Rock Formation",
  "Mendenhall Ice Caves",
  "Fingal’s Cave",
  "Ruby Falls",
  "Oneuli Beach",
  "Marble Caverns",
  "Nyaung Ohak",
  "Iguazu Falls",
  "The Doorway Railway",
  "Koekohe Beach",
  "Monolith Of Uluru",
  "Mount Roraima",
  "Danakil Depression",
  "Travertine Pools",
  "The Giant’s Causeway",
  "Pancake Rocks",
  "Lencois Maranhenses National Park",
  "Red Beach",
  "The Seven Giants",
  "Cat Island"
];
